[package]
name = "jito-bell"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "jito-bell"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.62"
borsh = "0.10.0"
chrono = "0.4.26"
clap = { version = "4.3.0", features = ["derive", "env"] }
env_logger = "0.11.3"
futures = "0.3.24"
log = "0.4.17"
maplit = "1.0.2"
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
solana-sdk = "1.17.6"
spl-stake-pool = { version = "^1.0.0", features = ["no-entrypoint"] }
thiserror = "2.0.12"
tokio = { version = "1.0.1", features = ["full"] }
tonic = "0.10.0"
yellowstone-grpc-client = "1.15.4"
yellowstone-grpc-proto = { version = "1.14.2", default-features = false }
