[workspace]
members = [
    "jito-bell",
    "stake-pool-parser"
]
resolver = "2"

[workspace.dependencies]
borsh = "0.10.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
solana-program = "2.2.1"
thiserror = "2.0.12"
yellowstone-vixen-core = "0.3.0"