programs:
  spl_stake_pool:
    program_id: "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
    instructions:
      deposit_stake:
        pool_mint: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"
        thresholds:
          - value: 0.1  # SOL
            notification:
              description: "JitoSOL stake deposit detected"
              destinations: ["telegram"]
          - value: 1000.0  # SOL
            notification:
              description: "Large JitoSOL stake deposit detected"
              destinations: ["telegram"]
          - value: 5000.0  # SOL
            notification:
              description: "Very large JitoSOL stake deposit detected"
              destinations: ["telegram", "slack"]
          - value: 10000.0  # SOL
            notification:
              description: "Whale JitoSOL stake deposit detected"
              destinations: ["telegram", "slack", "discord"]
      withdraw_stake:
        pool_mint: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"
        thresholds:
          - value: 0.1  # SOL
            notification:
              description: "JitoSOL stake withdrawal detected"
              destinations: ["telegram"]
          - value: 1000.0  # SOL
            notification:
              description: "Large JitoSOL stake withdrawal detected"
              destinations: ["telegram"]
          - value: 5000.0  # SOL
            notification:
              description: "Very large JitoSOL stake withdrawal detected"
              destinations: ["telegram", "slack"]
          - value: 10000.0  # SOL
            notification:
              description: "Whale JitoSOL stake withdrawal detected"
              destinations: ["telegram", "slack", "discord"]
      deposit_sol:
        pool_mint: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"
        thresholds:
          - value: 0.1  # SOL
            notification:
              description: "SOL deposit to JitoSOL detected"
              destinations: ["telegram"]
          - value: 1000.0  # SOL
            notification:
              description: "Large SOL deposit to JitoSOL detected"
              destinations: ["telegram"]
          - value: 5000.0  # SOL
            notification:
              description: "Very large SOL deposit to JitoSOL detected"
              destinations: ["telegram", "slack"]
          - value: 10000.0  # SOL
            notification:
              description: "Whale SOL deposit to JitoSOL detected"
              destinations: ["telegram", "slack", "discord"]
      withdraw_sol:
        pool_mint: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"
        thresholds:
          - value: 0.1  # SOL
            notification:
              description: "SOL withdrawal from JitoSOL detected"
              destinations: ["telegram"]
          - value: 1000.0  # SOL
            notification:
              description: "Large SOL withdrawal from JitoSOL detected"
              destinations: ["telegram"]
          - value: 5000.0  # SOL
            notification:
              description: "Very large SOL withdrawal from JitoSOL detected"
              destinations: ["telegram", "slack"]
          - value: 10000.0  # SOL
            notification:
              description: "Whale SOL withdrawal from JitoSOL detected"
              destinations: ["telegram", "slack", "discord"]
  
notifications:
  slack:
    webhook_url: "https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX"
    channel: "#jito-alerts"
  
  discord:
    webhook_url: "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  
  telegram:
    bot_token: "0123456789:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    chat_id: "-1001234567890"

message_templates:
  default: "{{description}} - Amount: {{amount}} SOL - Tx: https://explorer.solana.com/tx/{{tx_hash}}"
  slack: "<!here> {{description}} - Amount: {{amount}} SOL - <https://explorer.solana.com/tx/{{tx_hash}}|View Transaction>"
  discord: "@here {{description}} - Amount: {{amount}} SOL - [View Transaction](https://explorer.solana.com/tx/{{tx_hash}})"
